keeptrack/urls.py
"""
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from account import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_page,name='home-page'),
    
    path('skill/',include('skill.urls')),
    path('project/',include('project.urls')),
    path('account/',include('account.urls')),
    path('note/',include('note.urls')),
    
]

urlpatterns+= static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

note/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.note_page,name="note-page"),
    path('note-form/<pk>',views.note_form_page,name="note-form-page"),
    path('single-note/<pk>/<slug:slug_title>/',views.single_note_page,name="single-note-page"),
    path('note-form-update/<pk>',views.note_form_page_update,name="note-form-page-update"),
    path('bookmark-note/',views.bookmark_note_page,name="bookmark-note-page"),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    profile_image = models.ImageField(null=True,blank=True,upload_to='keeptrack/images/',default = 'keeptrack/default_images/default_profile_i2ejjp.png')
    username = models.CharField(max_length=255)
    first_name = models.CharField(max_length=255,null=True,blank=True)
    last_name = models.CharField(max_length=255,null=True,blank=True)
    bio = models.TextField(max_length=1000,blank=True,null=True)
    email = models.EmailField(max_length=255,blank=True,null=True)
    portfolio_site = models.URLField(max_length=500,blank=True,null=True)
    facebook = models.URLField(max_length=2000,blank=True,null=True)
    linkedin = models.URLField(max_length=2000,blank=True,null=True)
    youtube = models.URLField(max_length=2000,blank=True,null=True)

    coin = models.IntegerField(default=100,null=True,blank=True)

    def add_coin(self,coin):
        self.coin += coin
        self.save()
    
    def reduce_coin(self,coin):
        self.coin -= coin
        self.save()

    def __str__(self):
        return self.username


class Inbox(models.Model):
    owner = models.OneToOneField(Profile, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.owner.username

class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE,null=True)
    inbox = models.ForeignKey(Inbox, on_delete = models.CASCADE)
    body = models.TextField(max_length=2000)
    sent_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-sent_at']


# signals
def createProfile(sender, instance, created, **kwargs):
    if created:
        user = instance
        profile = Profile.objects.create(
            user=user,
            username = user.username,
            email = user.email,
            first_name = user.first_name,
            last_name = user.last_name,
        )
        Inbox.objects.create(owner = profile)
post_save.connect(createProfile,sender=User)



@receiver(post_delete,sender=Profile)
def deleteUser(sender,instance,**kwargs):
    try:
        user = instance.user
        user.delete()
    except:
        pass

@receiver(post_save,sender=Profile)
def updateUser(sender,instance,created,**kwargs):
    profile = instance
    user = profile.user
    if created == False:
        if profile.first_name:
            user.first_name = profile.first_name
        if profile.last_name:
            user.last_name = profile.last_name
        if profile.email:
            user.email = profile.email
        user.username = profile.username
        
        user.save()

notification/models.py
from django.db import models

# from django.contrib.contenttypes.models import ContentType
# from django.contrib.contenttypes.fields import GenericForeignKey

from account.models import Profile
# Create your models here.


class Notification(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    body = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KeepTrack</title>
    <link rel="icon" type="image/x-icon" href="{% static 'svg/navicon.svg' %}">
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script defer src="{% static 'js/all.js' %}"></script>
</head>
<body class="position-relative">
    <div id="top"></div>
    <a href="#top" class="btn btn-primary shadow py-2 px-3 position-fixed bottom-0 end-0 rounded-circle" style="z-index: 100;"><i class="fas fa-arrow-up"></i></a>

    {% include 'navbar.html' %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show fixed-top" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <p>{{message}}</p>
      </div>
    {% endfor %}
    {% endif %}
    
    {% block content %}
    {% endblock %}

    <footer class=" py-4 shadow" id="custom-bg" style="margin-top: 7rem;">
        <div class="container p-3">
            <h3 class="mb-4 text-center text-light">FAQ</h3>
          <div class="accordion accordion-flush w-75 mx-auto" id="accordionFlushExample">

            <div class="accordion-item">
              <h2 class="accordion-header" id="flush-headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                  <h5>Why do we need coins <i class="fas fa-coins"></i> ?</h5>
                </button>
              </h2>
              <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body"><p>You need coins <i class="fas fa-coins"></i> to feature your notes in the home page so that other users can find your notes. It costs 50 coins <i class="fas fa-coins"></i> to feature a single note.</p></div>
              </div>
            </div>

            <div class="accordion-item">
              <h2 class="accordion-header" id="flush-headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                  <h5>How do we earn coins <i class="fas fa-coins"></i> here?</h5>
                </button>
              </h2>
              <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body"><p>You are initially given 100 coins <i class="fas fa-coins"></i>. You also earn 25 coins <i class="fas fa-coins"></i> every time you share feedbacks to others featured notes. Remember we grow by lifting others.</p></div>
              </div>
            </div>

            <div class="accordion-item">
              <h2 class="accordion-header" id="flush-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                  <h5>How do we gain skill levels here?</h5>
                </button>
              </h2>
              <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body"><p>You gain points on a certain skill by adding projects and notes related to that skill. When a ceratin amount of point is gained, you reach a new level. For each project related to a skill, you gain 50 points on that skill. For each note related to a skill, you gain 25 points on that skill.</p></div>
              </div>
            </div>


          </div>
          <p class="text-center text-light mt-5 mb-3">© All rights reserved by Jami Islam Anik</p>
        </div>
      </footer>


    <script src="{% static 'js/bootstrap.bundle.js' %}">
    </script>
</body>
</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light mb-5 shadow-lg" id="custom-bg">


  <div class="container-fluid p-3 p-md-5">
    <a class="navbar-brand fs-2 text-light fw-bold" href="{% url 'home-page' %}">
      <img src="{% static 'svg/navicon.svg' %}" alt="icon" class=" bg-transparent"
        width="72" height="72">
      KeepTrack
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 px-4 fs-3">

        {% if user.is_authenticated %}
        <li class="nav-item dropdown me-5 mb-3 mb-md-0">
          <button class="btn btn-outline-light dropdown-toggle text-uppercase" id="navbarWithDropdown"
            data-bs-toggle="dropdown" role="button" aria-expanded="false">Skill</button>
          <div class="dropdown-menu" aria-labelledby="navbarWithDropdown">
            <a class="dropdown-item text-uppercase" href="{% url 'skill-page' %}">My Skills</a>
            <a class="dropdown-item text-uppercase" href="{% url 'skill-form-page' %}">Add Skill</a>
          </div>
        </li>

        <li class="nav-item dropdown me-5 mb-3 mb-md-0">
          <button class="btn btn-outline-light dropdown-toggle text-uppercase" id="navbarWithDropdown"
            data-bs-toggle="dropdown" role="button" aria-expanded="false">Project</button>
          <div class="dropdown-menu" aria-labelledby="navbarWithDropdown">
            <a class="dropdown-item text-uppercase" href="{% url 'project-page' %}">My Projects</a>
            <a class="dropdown-item text-uppercase" href="{% url 'project-form-page-create' %}?page=create">Add
              Project</a>
          </div>
        </li>

        <li class="nav-item dropdown me-5 mb-3 mb-md-0">
          <button class="btn btn-outline-light dropdown-toggle text-uppercase" id="navbarWithDropdown"
            data-bs-toggle="dropdown" role="button" aria-expanded="false">Note</button>
          <div class="dropdown-menu" aria-labelledby="navbarWithDropdown">
            <a class="dropdown-item text-uppercase" href="{% url 'note-page' %}">My Notes</a>
            <a class="dropdown-item text-uppercase" href="{% url 'bookmark-note-page' %}">Bookmarks</a>
          </div>
        </li>
        {% endif %}

        <li class="nav-item dropdown me-5 mb-3 mb-md-0">
          <button class="btn btn-outline-light dropdown-toggle text-uppercase" id="navbarWithDropdown"
            data-bs-toggle="dropdown" role="button" aria-expanded="false">Account</button>

          <div class="dropdown-menu" aria-labelledby="navbarWithDropdown">
            {% if user.is_authenticated %}


            <a class="dropdown-item text-uppercase" href="{% url 'account-page' user.profile.username %}">Profile</a>
            <a class="dropdown-item text-uppercase" href="{% url 'inbox-page' %}">My Inbox</a>
              <form action="{% url 'home-page' %}" method="POST">
                {% csrf_token %}
                <button type="submit" name="action" value="logout"
                  class="btn dropdown-item me-5 mb-3 mb-md-0">LOGOUT</button>
              </form>

              
            
            {% else %}
            
              <a href="{% url 'login-page' %}" class="btn dropdown-item me-5 mb-3 mb-md-0">LOGIN</a>
            
              <a href="{% url 'register-page' %}" class="btn dropdown-item me-5 mb-3 mb-md-0">SIGN UP</a>
          
            {% endif %}
          </div>

        </li>

      </ul>
      
      {% if user.is_authenticated %}

      
      <button class="btn ms-4 me-2 shadow text-light" data-bs-toggle="modal"
                    data-bs-target="#notificationModal"><span class="ps-1"><i class="fas fa-bell fa-bounce pe-1"></i>
                      {{ user.profile.notification_set.count }}
                    </span>
                </button>
                <div class="modal fade" id="notificationModal" tabindex="-1" aria-labelledby="notificationModalTitle"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="notificationModalTitle">Notifications</h5>
                                <form action="{% url 'home-page' %}" method="POST">
                                  {% csrf_token %}
                                  <button class="btn mx-2" type="submit" name="action" value="notification-delete" title="Delete all notifications?"><i class="fas fa-trash"></i></button>
                                </form>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                              {% for notification in user.profile.notification_set.all %}

                              <div class="shadow-sm px-3 py-2">
                              <span><i class="fas fa-bell pe-2"></i></span>
                                <p class="d-inline" style="line-height: 20px;">{{ notification.body }} <small>at {{ notification.created_at }}</small></p>
                                
                              </div>
                                
                              {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>

      <a href="{% url 'inbox-page' %}" class="btn text-light p-2 me-2 shadow rounded my-2"><i class="fas fa-message fa-bounce pe-1"></i>{{ user.profile.inbox.message_set.count }} </a>
      <a href="{% url 'note-page' %}" class="btn text-light p-2 me-2 shadow rounded my-2"><i class="fas fa-coins fa-bounce pe-1"></i>{{ user.profile.coin }} </a>

      {% if user.is_superuser %}
      <a href="{% url 'dashboard' %}" class="btn text-light p-1 px-2 me-2 shadow rounded my-2"><i class="fas fa-database fa-bounce pe-1"></i></a>
      {% endif %}

      {% endif %}

      <form class="d-flex my-2" method="POST" action="{% url 'home-page' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search Users by username..." aria-label="Search" name="searched">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>